sudo: required
services:
- docker
language: node_js
node_js: node
script:
- make lint
- make critique
before_deploy:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- make docker
deploy:
- provider: script
  script: make google-drive
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: ONdx0+AAMdLAd+dDezwEDKXr9bYZzXQo+OgH21CndNHUm+7ET6LaoWf+To1oymI5eeXsfWqqdVGBjpdkj+c84DlJ7pnQBokbq3+Jc/WT68swrTyOq8qgnuOyhV3cxD7pSMTb9XAh0CNVliOD/zU0h6xBjaj2Jpxf6XlLovaZi95QRcNLRDrir5Ra4kDywFysdjhvUV5LzF7CpDA9WlBwEZFo93nia79WENAdr8k89Z84E/3jM0juynAisj4MmS7NGKqnnEHe0vWyMdvAdV3g7cgpNQjMo2WwtU6uWJ+mOMG3BL01kXjnUyIHW9AFHDg3U8QgVNUf1bzcsb7nYLuxL3VQzXLqUA0oC9lc8c2wVZwd6Z/N+CV89/uAOr4zNzu1G6BgBNk/fYonhh/5DDLGuEYqeTQpj7ObbZqo36FC4WBqAVgiajXdHOgvXrHYsyv5kHOLx5k5utZvXp3M0Yzcb31QQGpEDdj5wIs8UdytMNryH8U20XADyX+K+G0023lRW1h4d3o8z7+PlTb5VGssDleXkdpuEIOhYseTQcBWhOgCIwKqmXDfdXBIT2taBZ61AzrYKLl72DDusiKN04Y4Kpd58jdeLpOv7mkruOl0BOHdgQqxxhxVb3fz6HS4g9npLkOfm/ccuwyZq3YytWw3scUsMt3y0YQ0IU7GKySC7Lo=
  skip_cleanup: true
  file_glob: true
  file: build/*
  on:
    tags: true
env:
  global:
  - secure: FwOsZ0JT0rG6Xvk4GVcnnujE14wTIOJm4om/RjSKadX6epIxLT9cDhMiRQ2w4WDGzstzKROV+1TLEV9s7V4/DrFfbv0riYM3rAMUOHZbFg7F4v+8pCFbbKRQnSyNnxlq+DcyXVxCods9s3H2O2Nw8rl/cnfP8b+Zis1Pt3wpxTGPDBA8wv4mlr5Q1JCDi6npdzgJe1Mbf+OzZ4rtnmgqfNVnpCFWfrjXoNGKujHci8m+6QEwOOoc0DgBoqRkGLqldo5ecSSwoRreWpSU9TwE5/NRMm7230wFocbhkbD9rY3p2LdfvPcKx0mEb9+WOonG8QJE9HFAz/epkELP0O3/wmHwnVQP/UwneTixJoOUAJIXlRClW0ikkfOdaU6YIXDRivl9JbPaBZ0RqXrntexs4kCOtiSYykCZIGNuzDQRWz8n5+RAvglOTnxU73E1GxtvCLKTpagQkUUdBOvdBtLXX+NUOkspmgZRPB5L0M3xOwgyytaxkB1+yspStOI3eiNzTV7/ACDyb5LyFfnmH1GJP6pnCuDvundfrbOz+6J8zLgfplMVv2/Ouj+4kz1QPWJ2UVT39JM6aoaVEvVx8oLsjFhCfA+DvzcNWo5eas/5MRaqW5ApNc2XNQkr/yybHc2HQJleRQvRAMQa0WMhFI+AIOU5Y2GWPbRVfG7PVdAFsGs=
  - secure: Pz1XU2WtVv1KWJdmEMjn1zLBSPyumxiYfy9/IvISYUKBoH50HHZWBPytoid9rX40KzWgB3FR5/huiv2tywDG5SUx//8lLQPZ7l+RvGzA7lht2vaJHZ/ToThvqcDo9BA5yqzsyuThBMEikC6NNhamKVq3L04ZztZmqlvTVyWz+ACTqZf6jsZ/5F0pFty7TIrKranIoj2bN+WscgZeWex99lNM/H45JY5wyIXHdXWRN5XTaEoKFisrbcnwKZqJVnvAwEJCpdoHd+BinfR8I6oa8xsxYUb+h8oSgTiiwWWLv4QLl3lXNGCMiYQ0dW4SWoVSgdBPyXxdKx1VVVkksDPH0bbr7EeLJQnBHbCJeL2tBbWHHkcnDp5IBn0GFPXKyS1TRc5ECsuy7d8RuHMVNfmZseo97grVyOkplDkd1PM/HLhUWqPgheaKat6c5oJOYwH04JeiIl3gur4n4feYRLFZsQXMkcrL6MbJozEC3g76x2XAgWKaJ2aNVq56BP7WUPqR9kxM3ulxeUv9o51UPvdkFuCzwy9GTnwwdX5lom3bTGIOrdbziPskkSf80HQbGxiUIAlgzLs236rJpoF2qzDtVJLXANN+PfUyxNhzEQra5NZbOBHstoCHiRwOnCrRVogBSN9sPr9qvGqjPt3AT1dMByX9xW9WXarxv4bAzpgM0p8=
  - secure: lheiME2K03gM9lb/KvvHHmfMz7ykqFQT6YtVXBwGu21LmvCyvuq7G1qK5A/jZr3NDAeBKC5bL/86Mdnh+rV3BcSGQXoXbS9t60zuJY95z8a/xIUvlg7cSJ/OMUpEvSXC0vOm+QxKTUwMVYT1m5Vn/hnU89U/DVDr2tEuZw+qq+Mv4gbAfMbGE+TmALjYsfHlKKA0kuL5g/ny3juomGxEkw+6DlTDjpousOAi8If/il/neimGvP/RQ+a0aq4YfflnCoDI0UkaUgjaSphbhbrm/7GMMiB88fHVRFeOAti872fOnuv1VoRcpJBU1efC2y5vX0PbfIOLPtA+o8evLNxMdT0zywje71RoxVIxX2NDjovdgWtaOwrT28o+Cm2rxZTEXX3FmTEmny7zLn5cHR4b1SakFJ5JEAOHCQRkcnjHDIz44494oxmkcgcFK0CaaZtEIXKIdAQ5JXuS+Jl3rQuabNikSrI1ORZXOHP5vQ5A+y7Rsx7g8DS+FavNylXf+RvhwKkniUZYADyP0rFsgzp3l5sJqFSBf5csuSnTYJ//KTFVI49LDEIfWl1Gz3QeQ2J1AXg7Nb6q+VitGmWqfhb8kHuHr/TIqeWQHPC/VzEG+IunphCt1cFU0ltWfcYjqd29q/pi7TbtqZHKha9HjGH6hogqEi8q4AweH8VRdSo7ZiM=
